name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Poetry
        run: |
          pip install poetry

      - name: Instalar dependências
        run: |
          poetry install

      - name: Rodar testes e cobertura
        run: |
          poetry run pytest --cov=src --cov-report=xml

      - name: Upload do relatório de cobertura
        uses: actions/upload-artifact@v3
        with:
          name: cobertura-xml
          path: coverage.xml

      - name: Build Docker (API)
        run: |
          docker build -f Dockerfile_api -t visiovox-api:ci .

      - name: Build Docker (Worker)
        run: |
          docker build -f Dockerfile_worker -t visiovox-worker:ci . 